- name: Gather facts from Arista EOS
  hosts: arista
  gather_facts: false
  connection: httpapi

  tasks:
    - name: Collect EOS facts
      arista.eos.eos_facts:
      register: eos_facts

    - name: Show facts
      debug:
        var: eos_facts.ansible_facts
